"""
Auto Email Sender - Sends weekly report and alerts to managers
"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from alert_monitor import AlertMonitor
from weekly_report_generator import WeeklyReportGenerator

class AutoEmailSender:
    """Send automated emails to managers with report and alerts"""
    
    def __init__(self, smtp_server='smtp.gmail.com', smtp_port=587):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        # You'll need to configure these
        self.sender_email = None
        self.sender_password = None
        self.manager_emails = []
    
    def configure(self, sender_email, sender_password, manager_emails):
        """Configure email credentials (call this before sending)"""
        self.sender_email = sender_email
        self.sender_password = sender_password
        self.manager_emails = manager_emails
    
    def send_weekly_report(self):
        """Generate and send weekly report to managers"""
        print("\n📧 Preparing weekly email for managers...")
        
        # Generate report and check alerts
        report_gen = WeeklyReportGenerator()
        report_path = report_gen.generate_report()
        
        alert_monitor = AlertMonitor()
        alerts = alert_monitor.check_all_kpis()
        
        # Create email
        subject = f"Management Weekly Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Email body
        alert_summary = alert_monitor.get_alert_summary()
        
        body = f"""
Hello Managers,

Please find attached the weekly management report.

Executive Summary:
- Total Alerts: {alert_summary['total_alerts']}
- High Priority Issues: {alert_summary['high_count']}
- Medium Priority Issues: {alert_summary['medium_count']}

Top Alerts:
"""
        for alert in alert_summary['alerts'][:3]:
            body += f"\n[{alert['severity']}] {alert['category']}: {alert['message']}"
            body += f"\n   Action: {alert['action']}\n"

        body += """

Action Items:
1. Review attached report for detailed metrics
2. Address high-priority alerts immediately
3. Schedule weekly review meeting to discuss action plan

This email was auto-generated by Management Operations Dashboard.

Best regards,
Automated Management System
"""
        
        return self._send_email(subject, body, report_path)
    
    def _send_email(self, subject, body, attachment_path=None):
        """Send email with optional attachment"""
        if not self.sender_email or not self.manager_emails:
            print("⚠️ Email not configured. Please run configure() first.")
            print("\nTo set up email:")
            print("1. Create a Gmail account for automated emails")
            print("2. Enable 'Allow less secure apps' or create App Password")
            print("3. Run: sender.configure('your_email@gmail.com', 'password', ['manager1@company.com'])")
            return False
        
        msg = MIMEMultipart()
        msg['From'] = self.sender_email
        msg['To'] = ', '.join(self.manager_emails)
        msg['Subject'] = subject
        
        msg.attach(MIMEText(body, 'plain'))
        
        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    'Content-Disposition',
                    f'attachment; filename={os.path.basename(attachment_path)}'
                )
                msg.attach(part)
        
        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            print(f"✅ Email sent to {len(self.manager_emails)} recipient(s)")
            return True
        except Exception as e:
            print(f"❌ Failed to send email: {e}")
            return False
    
    def test_configuration(self):
        """Test email configuration without sending full report"""
        test_body = "Test email from Management Operations Dashboard. Configuration successful."
        return self._send_email("Test Configuration", test_body)

if __name__ == "__main__":
    # Example usage
    sender = AutoEmailSender()
    
    # UNCOMMENT AND CONFIGURE FOR ACTUAL USE:
    # sender.configure(
    #     sender_email='your_automated_email@gmail.com',
    #     sender_password='your_app_password',
    #     manager_emails=['manager1@company.com', 'manager2@company.com']
    # )
    # sender.send_weekly_report()
    
    print("Email sender configured. Uncomment configuration to enable actual sending.")
    